---
title: "Data Manipulation"
author: "Fang Wang"
date: "2024-09-17"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, echo=FALSE, message = FALSE}
setwd("/Users/fangwang/Downloads/P8105 Data Science I/Lecture 6/data_manipulation")
library(tidyverse)
```

This document will show how to *manipulate* data.

Import the two datasets that we're going to manipulate:

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c ("NA", "", ".")) |>
  janitor::clean_names()

pups_df = 
  read_csv("data/FAS_pups.csv", na = c ("NA", "", ".")) |>
  janitor::clean_names()
```

## "select": to select variables

```{r}
select (litters_df, group, litter_number, gd0_weight)
```

```{r}
select (litters_df, group:gd18_weight)
```


```{r}
select (litters_df, -pups_survive)
```

```{r}
select (litters_df, -(group:gd18_weight))
```

```{r}
select (litters_df, starts_with("gd"))
```

```{r}
select (litters_df, contains("pups"))
```

```{r}
select (litters_df, GROUP = group) # select and rename

rename (litters_df, GROUP = group) # only rename 
# they are different.

select(litters_df, litter_number, gd0_weight, everything())

relocate (litters_df, litter_number, gd0_weight)
# the last two are the same.
```

```{r learning_assessment}
select (pups_df, litter_number, sex, pd_ears)
```


## "filter"

```{r}
filter(litters_df, gd_of_birth == 20)
filter(litters_df, gd_of_birth == 19)
```

```{r}
filter(litters_df, pups_born_alive > 8)
filter(litters_df, pups_born_alive >= 8)
filter(litters_df, pups_born_alive != 9)
```

```{r}
filter(litters_df, group == "Low8")
filter(litters_df, group == c("Low7", "Low8"))
filter(litters_df, group %in% c("Low7", "Low8"))
```

```{r}
filter(litters_df, 
       group %in% c("Low7", "Low8"), 
       pups_born_alive == 8)

filter(litters_df, 
       group %in% c("Low7", "Low8") | # either...or...
         pups_born_alive == 8)
```

```{r}
drop_na(litters_df)
drop_na(litters_df, gd0_weight)
```

```{r}
filter(pups_df, sex == 1)
filter(pups_df, sex == 2, pd_walk < 11)
```

## "mutate"

```{r}
mutate (litters_df, wt_gain = gd18_weight - gd0_weight)

mutate(litters_df, sq_pups = pups_born_alive^2)

mutate(litters_df, group = str_to_lower(group))

mutate (litters_df, 
        wt_gain = gd18_weight - gd0_weight,
        group = str_to_lower(group),
        )
```

## "arrange"

```{r}
arrange (litters_df, gd0_weight) # arrange observations instead of variables. 

arrange (litters_df, desc(gd0_weight))

arrange(litters_df, pups_born_alive, gd0_weight) #like "sort" in excel.
```

## "piping"

Do this using piping:
```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c ("NA", "", ".")) |>
  janitor::clean_names() |>
  select (-pups_born_alive) |>
  filter (group == "Con7") |>
  mutate (wt_gain = gd18_weight - gd0_weight) 

write_csv(litters_df, "data/cleaned_fas_litters.csv")

# hot key for |> : command + shift + M
```


```{r}
```

